create schema if not exists task_tracker;

create table if not exists task_tracker.project
(
    id              integer generated by default as identity,
    name            varchar(255) not null,
    start_date      timestamp,
    completion_date timestamp,
    status          varchar(80),
    priority        integer,
    primary key (id)
);

create table if not exists task_tracker.task
(
    id          integer generated by default as identity,
    name        varchar(255) not null ,
    description varchar(255),
    status      varchar(80),
    priority    integer not null,
    project_id  integer references task_tracker.project (id),
    primary key (id)
);
